<?php

namespace AppBundle\Repository;

/**
 * SortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortRepository extends \Doctrine\ORM\EntityRepository
{
}
