<?php

namespace AppBundle\Repository\TreeNursery;

/**
 * TreeKindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreeKindRepository extends \Doctrine\ORM\EntityRepository
{
}
