<?php

namespace AppBundle\Repository\TreeNursery;

/**
 * UsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsageRepository extends \Doctrine\ORM\EntityRepository
{
}
