<?php

namespace AppBundle\Repository\TreeNursery;

/**
 * VarietyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VarietyRepository extends \Doctrine\ORM\EntityRepository
{
}
