app_sort:
    resource: "@AppBundle/Controller/TreeNursery/SortController.php"
    type:     annotation

app_variety:
    resource: "@AppBundle/Controller/TreeNursery/VarietyController.php"
    type:     annotation

api:
    resource: '.'
    type: 'api_platform'
    prefix: /api

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
