<?php

namespace AppBundle\Repository\TreeNursery\TreeProperty;

/**
 * FlowerColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowerColorRepository extends \Doctrine\ORM\EntityRepository
{
}
